# Generated by Django 3.0.5 on 2020-04-16 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_index', '0002_auto_20200416_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 7, 46, 7, 281657), verbose_name='DatePublished'),
        ),
    ]
